---
- name: Ensure linux-headers are installed
  apt:
    name: "linux-headers"
    state: present

- name: Ensure ZFS packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zfs-dkms

- name: Load ZFS modules
  modprobe:
    name: zfs
    state: present
