---
- name: Update APT cache
  apt: update_cache=yes

- name: Ensure contrib repository is enabled
  apt_repository:
    repo: deb http://ftp.se.debian.org/debian/ stretch main contrib non-free
    state: present

- name: Ensure linux-headers are installed
  apt:
    name: "linux-headers"
    state: present

- name: Ensure ZFS packages are installed
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zfs-dkms

- name: Load ZFS modules
  modprobe:
    name: zfs
    state: present
