---
- name: Ensure Dom0 packages are installed
  apk:
    name: "{{ item }}"
    state: present
  with_items:
    - grub-xenhost
    - lvm2
    - pciutils
    - tmux
    - xen
    - xen-hypervisor

# TODO: only on initial
- name: Setup Dom0
  command: setup-xen-dom0

- name: Ensure xen-pci scripts are created
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: xen-pci.init.j2
      dest: /etc/init.d/xen-pci
      mode: 755
    - src: xen-pci.conf.j2
      dest: /etc/conf.d/xen-pci
      mode: 644

- name: Ensure xen-pci is enabled and started
  service:
    name: xen-pci
    enabled: true
    state: restarted

- name: Use tmux for xen consoles
  lineinfile:
    path: '/etc/conf.d/xendomains'
    regexp: '^XENDOMAINS_CONSOLE='
    line: 'XENDOMAINS_CONSOLE="tmux"'
    insertafter: '^#XENDOMAINS_CONSOLE='
